version: '3.6'

services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${SPRING_DATASOURCE_NAME}"
      POSTGRES_USER: "${SPRING_DATASOURCE_USERNAME}"
      POSTGRES_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres

volumes:
  postgres: {}