version: '3.6'

services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${SPRING_DATASOURCE_NAME}"
      POSTGRES_USER: "${SPRING_DATASOURCE_USERNAME}"
      POSTGRES_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres

  app:
    container_name: ripple_reach
    restart: unless-stopped
    env_file:
      - .env.staging
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_NAME: "${SPRING_DATASOURCE_NAME}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      JWT_EXPIRATION_TIME: "${JWT_EXPIRATION_TIME}"
      STORAGE_BUCKET: "${STORAGE_BUCKET}"

volumes:
  postgres: {}