runtime: java21
instance_class: F1
env_variables:
    SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    SPRING_DATASOURCE_NAME: ${SPRING_DATASOURCE_NAME}
    SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    STORAGE_BUCKET: ${STORAGE_BUCKET}
