CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    TEXT                                    NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    content    TEXT                                    NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE post_attachment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name          VARCHAR(255)                            NOT NULL,
    url                VARCHAR(255)                            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    post_attachment_id BIGINT,
    CONSTRAINT pk_postattachment PRIMARY KEY (id)
);

CREATE TABLE upvote
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    post_id    BIGINT,
    comment_id BIGINT,
    CONSTRAINT pk_upvote PRIMARY KEY (id)
);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES app_user (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE post_attachment
    ADD CONSTRAINT FK_POSTATTACHMENT_ON_POST_ATTACHMENT FOREIGN KEY (post_attachment_id) REFERENCES post (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES app_user (id);

ALTER TABLE upvote
    ADD CONSTRAINT FK_UPVOTE_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);

ALTER TABLE upvote
    ADD CONSTRAINT FK_UPVOTE_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE upvote
    ADD CONSTRAINT FK_UPVOTE_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE role
    ALTER COLUMN name SET NOT NULL;